name: Build
on:
  push:
  pull_request:

jobs:
  build-project:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: |
            CMAKE_BUILD_TYPE=Release
          build-args: --config Release
