name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-project:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: build/libsqlite_bignum.so
            asset_name: sqlite_bignum-linux-amd64
          - os: windows-latest
            artifact_name: build/Release/sqlite_bignum.dll
            asset_name: sqlite_bignum-windows-amd64
          - os: macos-latest
            artifact_name: build/libsqlite_bignum.dylib
            asset_name: sqlite_bignum-macos-amd64

    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.2

      - name: Build project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: |
            CMAKE_BUILD_TYPE=Release
          build-args: --config Release

      - name: List files for debugging
        run: ls -R build

      - name: Compress files
        uses: vimtor/action-zip@v1.2
        with:
          files: ${{ matrix.artifact_name }}
          dest: ${{ matrix.asset_name }}.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}.zip
          asset_name: ${{ matrix.asset_name }}.zip
          tag: ${{ github.ref }}